language: python
install: pip install petroglyph
script: bash deploy.sh
branches:
  only:
  - master
env:
  global:
    secure: i/emjh9YTAYkQzdkFudzPt3Znb/cZUY/z/qN9rfhCvS62NLqiDB/M8KCQY8+u38WXP23A4azmjn9nUEjwGnrZT4tBUppilQlFgXWu3nE9sO76LXPZVp19IZ/Xp4H0KFNG5lHRNjaS4otFh2yUSBNZGsJRq8TJ9TrkWym0IZg6y3jx0qP4ACx/DUN/i1Hh+roLQyaiLFs7zRTS4XhNqflXHiUk8fFOVo3XLEJlD+KNKv/icPSR6EizbWe+OnCHYdfGQ2l/0ZN9HvJqUW+6MGWScP7uLiJw0VthnctDOEFLI+CBMtq32qCTDpS1U3Z1KFihUzMFdvftHa34vwwlPUhrhXJciUz3aOoJGhUhvb7REXgakBGe0FlF2Dr8p/bhDQcx3kQ93KgogJ7Xe2osnyMLxkW5LJUQ9rfEjG6Q1qHdb6mAKWjTV5LlFDLoGhxRcE4EcFEaBeqVcfGTpL7w53HZcM8cHfYXMJ/PgY9LtEcX64E6fLLYp6paF75KRtJi2N9Y/cImNqbYCe5aO82xzPmMGH10aFN4PHcQphX/QJbcdy+vov2OJWKqzG9Uk+5W8p8CXrumOh5P8m2cJUqos5wfz+3wga6C3UvPSmw3vMYUf+Vgp7Vw26O89GxKAbYqPIz5TZUSVNBEOYNHvtKC9ZOHzuqhKNfnWhrJTQfimTuWBA=
