language: python
install: pip install petroglyph
script: bash deploy.sh
branches:
  only:
    - master
env:
  global:
    secure: khwl12cNp/UjuaN0pBjKmXrGgAW25wAJbloATJEzaqnIS0ppIyproUpN0eJN8gybioPQ7yUEAX1eOOKTaM0zgPo1azg6uduRcbGs7haztEHn0DstjSubetlIEHhFY0l/YbZhLV7f1EWc1iT2q5MvMY4kkoKxjLZ5Mi57lQh5EJrtBAV3cF3k09cGIPjaLBUG48jtji/EhRPgs5juub+rw6dY1S9BYoTLhwnDHyGYc5kcvFw7aKH2JrcIwNLNwh8j+NzIdG83FpKP2z96HH3nRIBjnDw8dHXMkSwI1g4nPD8z539R3PKoy/+hRFra76Bwtnmsqgzxc4ZVKUpU/my+Qql12Fm8+z9e5JlGOdxk/NYPhsZQt0UR9l+YD2h9xx2zDh8nmEQBsdwNdiK22JcFjfQm3/4ogxf1g2FLnMpAYgDI72mGUkxc7YHdVkw0pe45uhETmsRolpEqySJXzN1ITZJEztnuLqFlTwIGyDUCUTar3krcUncM59Nzg0GmQoOqRikmhKlMAkMYu3ABd3tAU/S2Gyg7vixwU9ZKNagDMjzC0bajNOPc9IaCMUO0bw0LQOlrB0bjVunqgZEIHqW4/u1F/uYXNATAiiYRl2sCCuS992PzK0QQx1u8wU7DAsvMUh1BWErIWVVEtYl9v05r03Te7QmTm1muuTPkXK30Lsc=
